spring:
  application:
    name: askopt-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/askops_db?currentSchema=askops_schema
    username: askops_admin
    password: 123456
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: ""       # 生产环境建议配置密码
      database: 0
      timeout: 5000ms

# 统一使用 MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.scb.askopt_backend.entity  # 统一实体类路径
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 生产环境建议移除或改为日志框架
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] [%thread] %-5level %logger{36} - %msg%n"
server:
  port: 8082
hmac:
  client-id: central-panel
  clients:
    central-panel: SUPER_SECRET_KEY_123

jwt:
  secret: demo-secret-key-demo-secret-key-demo-secret-key-demo-secret-key